import localFont from "next/font/local";
import "./globals.css";

// Components
import Header from "../components/Header";
import PageTransition from "../components/PageTransition";
import StairTransition from "../components/StairTransition";

const geistSans = localFont({
  src: "/font/google/Geist-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "/font/google/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
});

const jetbrainsMono = localFont({
  src: "/font/google/JetBrainsMono-VariableFont_wght.ttf",
  variable: "--font-jetbrains-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
